INSERT INTO public.incorrect_answer ("text",question_id) VALUES 
('Iacta alea est!',1)
,('Vidi, vini, vici',1)
,('Aegri somnia vana',1)
,('Chowder',2)
,('Pride',2)
,('Destruction',2)
,('42 mph',3)
,('13 mph',3)
,('9 mph',3)
,('3',4)
;
INSERT INTO public.incorrect_answer ("text",question_id) VALUES 
('9',4)
,('7',4)
,('M',5)
,('Z',5)
,('X',5)
,('Cowson',6)
,('Bicow',6)
,('Mooson',6)
,('Lake Baikal',7)
,('Lake Michigan',7)
;
INSERT INTO public.incorrect_answer ("text",question_id) VALUES 
('Lake Victoria',7)
,('Wild Wild West',8)
,('War World Web',8)
,('20',9)
,('55',9)
,('77',9)
,('Lilith',10)
,('Eve',10)
,('Hera',10)
,('London',11)
;
INSERT INTO public.incorrect_answer ("text",question_id) VALUES 
('Belgium',11)
,('Munich',11)
,('California',12)
,('Siberia',12)
,('China',12)
,('Van Gogh',13)
,('Picasso',13)
,('Da Vinci',13)
,('Number sign',14)
,('Hash Sign',14)
;
INSERT INTO public.incorrect_answer ("text",question_id) VALUES 
('Pound',14)
,('Japan',15)
,('Ethiopia',15)
,('Canada',15)
,('Bear',16)
,('Rabbit',16)
,('Seal',16)
,('Alaska',17)
,('Russia',17)
,('Washington',17)
;
INSERT INTO public.incorrect_answer ("text",question_id) VALUES 
('500',18)
,('200',18)
,('1000',18)
,('$0.25',19)
,('$1',19)
,('$5',19)
,('Receive withdrawls in rosary beads',20)
,('Vote for the Pope',20)
,('Purchase indulgences',20)
;